modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${license}"
issueTrackerURL="https://github.com/MinecraftForge/MinecraftForge/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/Bliss-tbh/Async-1.20.1"
logoFile="${mod_id}.png"
authors = "${mod_authors}"
description = '''${description}'''

[[mixins]]
config = "${mod_id}.common.mixins.json"

[[mixins]]
config = "${mod_id}.forge.mixins.json"

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"